name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter código do projeto
        uses: actions/checkout@v4
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            lipemiranda159/fake-shop:latest
            lipemiranda159/fake-shop:v${{ github.run_number }}
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar na AWS
        run: echo "EXECUTAR COMANDO AWS CONFIG"
      - name: Configurar o kubectl
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Aplicar os manifestos no Kubernetes
        run: echo "Executando kubectl apply"
  
